# Generated by Django 3.1.3 on 2020-11-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20201126_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='data/cv'),
        ),
        migrations.AlterField(
            model_name='languages',
            name='lv',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
