# Generated by Django 3.1.3 on 2020-11-26 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20201126_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languages',
            old_name='lv',
            new_name='level',
        ),
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=258)),
                ('university', models.CharField(blank=True, max_length=128)),
                ('dt', models.CharField(blank=True, max_length=128)),
                ('order', models.IntegerField(blank=True, default=1, null=True)),
                ('main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='data.main')),
            ],
            options={
                'ordering': ['-order'],
            },
        ),
    ]
